config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get '/about', to: 'homes#about'
  resources :users do
    resources :events, only: [:index, :create, :update, :destroy] do
      collection do
        get 'json' => 'events#json', as: 'events'          # users show画面への遷移を避ける為
      end
    end
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: :index
end

app/models/notification.rb
class Notification < ApplicationRecord
  # スコープ（新着順）
  default_scope -> { order(created_at: :desc) }

  # optional: trueはpost_idにnilを許可する為（belongs_toがつくカラムには自動的にallow_nil: falseが付与される）
  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true
  # 通知を送ったユーザーIDを参考にモデルへアクセス
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id',  optional: true
  # 通知を送られたユーザーIDを参考にモデルへアクセス
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id',  optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @user = current_user
    @events = Event.where(user_id: current_user.id)
    # サイドバーに本日の予定表示
    @today_events = @events.where("start <= ? AND end >= ?", Date.today.end_of_day, Date.today.beginning_of_day)
    # current_userの投稿に紐づいた通知一覧
    @notifications = current_user.passive_notifications
    # @notificationの中でまだ確認していない（indexに一度も遷移していない）通知のみ
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    # 通知を全削除
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path(current_user.id)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    @visiter = notification.visiter
    @post_comment = nil
    @your_post = link_to 'あなたの投稿', post_path(notification.post_id), style: "font-weight: bold;"
    @visiter_post_comment = notification.post_comment_id
    # notification.actionの種類が、favoriteかpost_commentかで分岐
    case notification.action
    when "favorite"
      tag.a(notification.visiter.name, href: user_path(@visiter), style: 'font-weight: bold;') + "が" + tag.a("あなたの投稿", href: post_path(notification.post_id), style: 'font-weight: bold;') + "にいいねしました。"
    when "post_comment"
      @post_comment = PostComment.find_by(id: @visiter_post_comment)&.comment
      tag.a(@visiter.name, href: user_path(@visiter), style: 'font-weight: bold;') + "が" + tag.a("あなたの投稿", href: post_path(notification.post_id), style: 'font-weight: bold;') + "にコメントしました。"
    end
  end

  # 未確認の通知
  def unchecked_notifications
    current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% post = notification.post %>
<div class="user-view clearfix">
  <%= link_to user_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg", size:"50x50", class: "m-3 rounded-circle" %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= "(#{time_ago_in_words(notification.created_at)}前)" %></span>
  <br>
  <% if !@post_comment.nil? %>
    <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @post_comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="user-info col-2">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-9 offset-md-1">
      <h1><i class="fas fa-paw"></i>通知一覧</h1>
        <%= link_to notifications_destroy_all_path(current_user.id), method: :delete do %>
          <i class="fas fa-trash" style="color: black;"></i>
          <h7 style="color: black;">全削除</h7>
        <% end %>
        <hr>
      <% if @notifications.exists? %>
        <div class="users-index">
          <%= render @notifications %>
        </div>
      <% else %>
        <p>通知はありません</p>
      <% end %>
    </div>
  </div>
</div>