config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get '/about', to: 'homes#about'
  resources :users do
    resources :events, only: [:index, :create, :update, :destroy] do
      collection do
        get 'json' => 'events#json', as: 'events'          # users show画面への遷移を避ける為
      end
    end
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :events, dependent: :destroy
  # 自分が作成した通知（active）、通知を送ったユーザーIDを参考にモデルへアクセス
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  # 自分宛の通知（passive）、通知を送られたユーザーIDを参考にモデルへアクセス
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 100 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # 新着順に５件ずつ表示
    @posts = @user.posts.page(params[:page]).per(5).reverse_order
    @events = Event.where(user_id: current_user.id)
    # サイドバーに本日の予定表示
    @today_events = @events.where("start <= ? AND end >= ?", Date.today.end_of_day, Date.today.beginning_of_day)
  end

  def index
    @users = User.all.page(params[:page]).per(10)
    @user = current_user
    @events = Event.where(user_id: current_user.id)
    # サイドバーに本日の予定表示
    @today_events = @events.where("start <= ? AND end >= ?", Date.today.end_of_day, Date.today.beginning_of_day)
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) if @user != current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報の更新に成功しました。"
      redirect_to user_path(@user.id)
    else
      render action: :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :start, :end)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<h2><i class="fas fa-paw"></i>ユーザー情報</h2>
  <div class="user-info">
    <div class="card mt-4 mb-4 shadow-lg">
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "m-3 rounded-circle"; %>
      <div class="card-body">
        <div class="row mx-auto">
          <h5><i class="fas fa-user"></i><%= user.name %></h5>
        </div>
        <div class="row mx-auto">
          <!--演算子使用し、nilでもnilを返すよう設定-->
          <%= user.introduction&.truncate(50) %>
        </div>
        <p>
          <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </p>
        <div class="row mx-auto">
          <!--未確認の通知がある際に黄色いマークでお知らせ-->
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
          <% end %>
          <h5>
            <%= link_to notifications_path(current_user.id), class: "btn-default, text-dark" do %>
              <i class="fas fa-bell"></i>通知一覧
            <% end %>
          </h5>
        </div>
        <div class="row mx-auto">
          <h5>
            <%= link_to user_events_path(current_user.id), class: "btn-default, text-dark" do %>
              <i class="fa fa-calendar"></i>本日の予定
            <% end %>
          </h5>
          <% if @today_events.exists? %>
            <% @today_events.each do |today_event| %>
              ・<%= today_event.title %><br>
            <% end %>
          <% else %>
            <p>・特になし</p>
          <% end %>
        </div>
        <p class="mt-2">
          <h5><i class="fas fa-camera-retro"></i>新規投稿</h5>
          <%= link_to "新規投稿", new_post_path, class: "btn btn-success" %>
        </p>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="container mt-5">
  <h1 class="row m-3"><i class="fas fa-paw"></i>ユーザー情報編集</h1>
  <div class="row">
    <div class="col-7 m-3">
      <!--バリデーションによるエラーメッセージ-->
      <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <%= @user.errors.count %>件のエラーが発生しました<br>
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        </div>
      <% end %>
      <!--ここまで-->
      <%= form_with model:@user, url:"/users/#{@user.id}", local:true do |f| %>
        <div class="form-group">
          <label for="inputName">ユーザー名</label>
          <p><%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "ユーザー名" %></p>
        </div>
        <div class="form-group">
          <label for="inputProfileImage">プロフィール画像</label>
          <p><%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %></p>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">自己紹介</label>
          <p><%= f.text_area :introduction, rows:'4', cols:'60' %></p>
        </div>
        <div class="form-group">
          <P><%= f.submit "更新", class: "btn btn-success" %></P>
          <p>
            <%= link_to "マイページへ", user_path(@user.id) %>
            |
            <%= link_to "ユーザー一覧へ", users_path %>
          </p>
        </div>
      <% end %>
    </div>
    <div class="col-2">
      <%= image_tag '1187328.jpg', size: '500x500' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="user-info col-2">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-9 offset-1">
      <h1><i class="fas fa-paw"></i>ユーザー一覧</h1>
      <div class="card-list-container p-3">
        <% @users.each do |user| %>
        <div class="row shadow-lg">
          <div class="col-2 my-auto">
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "mt-1 rounded-circle"; %>
          </div>
          <div class="col-2 my-auto">
            <h5><i class="fas fa-user"></i><%= user.name %></h5>
          </div>
          <div class="col-5 my-auto">
            <%= user.introduction %>
          </div>
          <div class="col-3 my-auto">
            <%= link_to "投稿を見る", user_path(user.id), class: "btn btn-primary" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="user-info col-2">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-9 offset-md-1">
      <h1><i class="fas fa-paw"></i>ユーザー投稿一覧</h1>
        <div class="card-list-container p-3">
          <% @posts.each do |post| %>
          <div class="row shadow-lg">
            <div class="col-4 my-auto">
              <%= link_to post_path(post.id) do %>
                <%= attachment_image_tag post, :post_image, :fill, 280, 300 %>
              <% end %>
            </div>
            <div class="col-8">
              <div class="card-body">
                <p>
                  <%= attachment_image_tag post.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", class: "mt-1 rounded-circle"; %>
                </p>
                <p class="card-title">
                  <%= link_to post_path(post.id), class: "text-dark" do %>
                    <h5 class="strong">
                      <i class="fas fa-paw"></i><span><%= post.title.truncate(20) %></span>
                    </h5>
                  <% end %>
                </p>
                <p class="card-text">
                  <%= post.body.truncate(120) %>
                </p>
                <span>
                  <% post.tags.each do |tag| %>
                    <span class="tag-label"><i class="fas fa-tag"></i> <%= tag.name %></span>
                  <% end %>
                </span>
                <br>
                <br>
                <p>
                  <span><i class="fas fa-user"></i> By <%= post.user.name %> | </span>
                  <span><i class="fa fa-calendar"></i> <%= post.created_at.strftime('%Y/%m/%d') %> | </span>
                  <span><i class="fa fa-comment"></i> <%= link_to "#{post.post_comments.count}", post_path(post.id), class: "text-dark" %> | </span>
                  <% if post.favorited_by?(current_user) %>
                    <span>
                      <%= link_to post_favorites_path(post.id), method: :delete, class: "text-danger" do %>
                        ❤<%= post.favorites.count %> いいね
                      <% end %>
                    </span>
                  <% else %>
                    <span>
                      <%= link_to post_favorites_path(post.id), method: :post, class: "text-dark" do %>
                        ♡<%= post.favorites.count %> いいね
                      <% end %>
                    </span>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
          <% end %>
        </div>
    </div>

  </div>
  <div class="row justify-content-center">
    <%= paginate @posts %>
  </div>
</div>