config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get '/about', to: 'homes#about'
  resources :users do
    resources :events, only: [:index, :create, :update, :destroy] do
      collection do
        get 'json' => 'events#json', as: 'events'          # users show画面への遷移を避ける為
      end
    end
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: :index
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :tags, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  attachment :post_image

  validates :post_image, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 300 }

  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "favorite"
    )
    notification.save if notification.valid?
  end

  def create_notification_post_comment!(current_user, post_comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    # コメントは複数回することが考えられる為、一つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    # 自分の投稿に対するコメントの場合は通知済に設定
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @posts = Post.all
    @user = current_user
    @post_comment = PostComment.new
    @events = Event.where(user_id: current_user.id)
    # サイドバーに本日の予定表示
    @today_events = @events.where("start <= ? AND end >= ?", Date.today.end_of_day, Date.today.beginning_of_day)
  end

  def index
    @posts = Post.all.page(params[:page]).per(5).reverse_order
    @user = current_user
    @events = Event.where(user_id: current_user.id)
    # サイドバーに本日の予定表示
    @today_events = @events.where("start <= ? AND end >= ?", Date.today.end_of_day, Date.today.beginning_of_day)
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "投稿情報の更新に成功しました。"
      redirect_to post_path(@post.id)
    else
      render action: :edit
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @posts = Post.all
    @post.user_id = current_user.id
    if @post.save
      # Google Vision APIの呼び出しとタグの作成
      tags = Vision.get_image_data(@post.post_image)
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      flash[:success] = "投稿に成功しました。"
      redirect_to post_path(@post.id)
    else
      @user = current_user
      render action: :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:info] = "投稿を削除しました。"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :post_image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container mt-5">
  <h1 class="row m-3"><i class="fas fa-paw"></i>投稿編集</h1>
  <div class="row">
    <div class="col-7 m-3">
      <!--バリデーションによるエラーメッセージ-->
      <% if @post.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <%= @post.errors.count %>件のエラーが発生しました<br>
          <% @post.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        </div>
      <% end %>
      <!--ここまで-->
      <%= form_with model:@post, url:"/posts/#{@post.id}", local:true do |f| %>
        <div class="form-group">
          <label for="inputPostImage">投稿画像</label>
          <p><%= f.attachment_field :post_image, placeholder: "投稿画像" %></p>
        </div>
        <div class="form-group">
          <label for="inputTitle">タイトル</label>
          <p><%= f.text_field :title, autofocus: true, placeholder: "タイトル" %></p>
        </div>
        <div class="form-group">
          <label for="inputBody">本文</label>
          <p><%= f.text_area :body, rows:'6', cols:'80' %></p>
        </div>
        <div class="form-group">
          <p><%= f.submit "更新", class: "btn btn-success" %></p>
          <p>
            <%= link_to "投稿詳細へ", post_path(@post.id) %>
            |
            <%= link_to "投稿一覧へ", posts_path %>
          </p>
        </div>
      <% end %>
    </div>
    <div class="col-2">
      <%= image_tag '1187328.jpg', size: '500x500' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="user-info col-2">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-9 offset-md-1">
      <h1><i class="fas fa-paw"></i>みんなの投稿一覧</h1>
        <div class="card-list-container p-3">
          <% @posts.each do |post| %>
          <div class="row shadow-lg">
            <div class="col-4 my-auto">
              <%= link_to post_path(post.id) do %>
                <%= attachment_image_tag post, :post_image, :fill, 280, 300 %>
              <% end %>
            </div>
            <div class="col-8">
              <div class="card-body">
                <p>
                  <%= attachment_image_tag post.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", class: "mt-1 rounded-circle"; %>
                </p>
                <p class="card-title">
                  <%= link_to post_path(post.id), class: "text-dark" do %>
                    <h5 class="strong">
                      <i class="fas fa-paw"></i><span><%= post.title.truncate(20) %></span>
                    </h5>
                  <% end %>
                </p>
                <p class="card-text">
                  <%= post.body.truncate(120) %>
                </p>
                <span>
                  <% post.tags.each do |tag| %>
                    <span class="tag-label"><i class="fas fa-tag"></i> <%= tag.name %></span>
                  <% end %>
                </span>
                <br>
                <br>
                <span>
                  <i class="fas fa-user"></i> By <%= post.user.name %> |
                </span>
                <span>
                  <i class="fa fa-calendar"></i> <%= post.created_at.strftime('%Y/%m/%d') %> |
                </span>
                <span>
                  <i class="fa fa-comment"></i> <%= link_to "#{post.post_comments.count}", post_path(post.id), class: "text-dark" %> |
                </span>
                <span id="favorites_buttons_<%= post.id %>">
                  <%= render partial: 'favorites/favorite', locals: { post: post} %>
                </span>
              </div>
            </div>
          </div>
          <% end %>
        </div>
    </div>

  </div>
  <div class="row justify-content-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <h1 class="row m-3"><i class="fas fa-paw"></i>新規投稿</h1>
  <div class="row">
    <div class="col-7 m-3">
    <!--バリデーションによるエラーメッセージ-->
    <% if @post.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <%= @post.errors.count %>件のエラーが発生しました<br>
        <% @post.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <!--ここまで-->
    <%= form_with model: @post, local: true do |f| %>
      <div class="form-group">
        <label for="inputPostImage">投稿画像</label>
        <p><%= f.attachment_field :post_image, placeholder: "投稿画像" %></p>
      </div>
      <div class="form-group">
        <label for="inputTitle">タイトル</label>
        <p><%= f.text_field :title, autofocus: true, placeholder: "タイトル" %></p>
      </div>
      <div class="form-group">
        <label for="inputBody">本文</label>
        <p><%= f.text_area :body, rows:'6', cols:'80' %></p>
      </div>
      <div class="form-group">
        <p><%= f.submit "新規投稿", class: "btn btn-success" %></p>
        <p><%= link_to "投稿一覧へ", posts_path %></p>
      </div>
    <% end %>
    </div>
    <div class="col-2">
      <%= image_tag '1187328.jpg', size: '500x500' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="user-info col-2">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-9 offset-md-1">
      <h1><i class="fas fa-paw"></i>投稿詳細</h1>
      <div class="post-detail py-5 bg-light">
        <div class="card w-75 mx-auto mt-4 shadow-lg">
          <%= attachment_image_tag @post, :post_image, class: "card-img-top"; %>
          <br>
          <div class="tag-box">
            <% @post.tags.each do |tag| %>
              <span class="tag-label"><i class="fas fa-tag"></i> <%= tag.name %></span>
            <% end %>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-2">
                <%= attachment_image_tag @post.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "mt-3 rounded-circle"; %>
              </div>
              <div class="col-10">
                <p class="card-title">
                  <%= link_to post_path(@post.id), class: "text-dark" do %>
                    <h5 class="strong">
                      <i class="fas fa-paw"></i><span><%= @post.title %></span>
                    </h5>
                  <% end %>
                </p>
                <p class="card-text">
                  <%= @post.body %>
                </p>
                <span><i class="fas fa-user"></i> By <%= @post.user.name %> | </span>
                <span><i class="fa fa-calendar"></i> <%= @post.created_at.strftime('%Y/%m/%d') %> | </span>
                <span><i class="fa fa-comment"></i> <%= link_to "#{@post.post_comments.count}", post_path(@post.id), class: "text-dark" %> | </span>
                <span id="favorites_buttons_<%= @post.id %>">
                  <%= render partial: 'favorites/favorite', locals: { post: @post} %>
                </span>
                <p class="card-action p-3">
                  <% if @post.user == current_user %>
                    <%= link_to "編集", edit_post_path(@post.id), class: "btn btn-success" %>
                    |
                    <%= link_to "削除", post_path(@post.id), method: :delete, data: {confirm: '本当に投稿を削除してもよろしいですか？'}, class: "btn btn-danger" %>
                  <% end %>
                </p>
              </div>
            </div>
            <hr>
            <div class="comments card-text">
              <h4 class="mt-3"><%= @post.post_comments.count %>件のコメント</h4>
              <% @post.post_comments.each do |post_comment| %>
                <div class="media border mb-3">
                  <%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "bd-placeholder-img align-self-center mx-3 rounded-circle" %>
                  <div class="media-body ml-4 p-3">
                    <p>
                      <span><i class="fas fa-user"></i> By <%= post_comment.user.name %> | </span>
                      <span><i class="fa fa-calendar"></i> <%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                    </p>
                    <p><%= post_comment.comment %></p>
                    <% if post_comment.user == current_user %>
                      <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, data: {confirm: '本当にコメントを削除してもよろしいですか？'}, class: "btn btn-danger pull-right" %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
            <hr>
            <div class="new-comment card-text">
            <!--バリデーションによるエラーメッセージ-->
            <% if @post_comment.errors.any? %>
              <div id="error_explanation" class="alert alert-danger">
                <%= @post_comment.errors.count %>件のエラーが発生しました<br>
                <% @post_comment.errors.full_messages.each do |message| %>
                  <%= message %>
                <% end %>
              </div>
            <% end %>
            <!--ここまで-->
              <%= form_with(model:[@post, @post_comment]) do |f| %>
                <div class="form-group">
                  <label for="inputComment">コメントする</label>
                  <%= f.text_area :comment, rows:'5', class: "form-control", placeholder: "コメントをここに" %>
                </div>
                <%= f.submit "送信する", class: "btn btn-lg btn-info mt-2 float-right" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>