config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get '/about', to: 'homes#about'
  resources :users do
    resources :events, only: [:index, :create, :update, :destroy] do
      collection do
        get 'json' => 'events#json', as: 'events'          # users show画面への遷移を避ける為
      end
    end
  end
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  delete 'notifications/destroy_all', to: 'notifications#destroy_all'
  resources :notifications, only: :index
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogsAndMePortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1c69022796.js" crossorigin="anonymous"></script>
    <!--レスポンシブ対応の為viewport読み込み（未完成）-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <!--FullCalendarの読み込み-->
    <title>FullCalendar</title>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css">
    <!--ここまで-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <div class="container">
        <div class="row">
          <div class="col align-self-center">
            <div class="navbar-brand p-1">
              <%= link_to root_path(current_user), data: {"turbolinks" => false} do %>
                <%= image_tag 'logo.jpg', size: '250x100' %>
              <% end %>
            </div>
          </div>
          <div class="col-align-self-center">
            <% if user_signed_in? %>
              <ul class="nav navbar-expand-lg navbar-right">
                <li class="nav-item m-3 pt-3">
                  <%= link_to user_path(current_user.id), class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-home"></i>ホーム
                  <% end %>
                </li>
                <li class="nav-item m-3 pt-3">
                  <%= link_to user_events_path(current_user.id), class: "btn btn-outline-secondary", data: {"tubolinks" => false} do %>
                    <i class="fa fa-calendar"></i>マイカレンダー
                  <% end %>
                </li>
                <li class="nav-item m-3 pt-3">
                  <%= link_to posts_path, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-camera-retro"></i>投稿一覧
                  <% end %>
                </li>
                <li class="nav-item m-3 pt-3">
                  <%= link_to users_path, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-users"></i>ユーザー一覧
                  <% end %>
                </li>
                <li class="nav-item m-3 pt-3">
                  <%= link_to destroy_user_session_path, method: :delete, data: {"turbolinks" => false}, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-sign-out-alt"></i>ログアウト
                  <% end %>
                </li>
              </ul>
            <% else %>
              <ul class="nav navbar-expand-lg navbar-right">
                <li class="nav-item m-3 pt-3">
                  <%= link_to root_path, data: {"turbolinks" => false}, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-home"></i>ホーム
                  <% end %>
                </li>
                <li class="nav-item m-3 pt-3">
                  <%= link_to about_path, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-dog"></i>サイト案内
                  <% end %>
                </li>
                <li class="nav-item m-3 pt-3">
                  <%= link_to new_user_registration_path, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-user-plus"></i>新規登録
                  <% end %>
                </li>
                <li class="nav-item m-3 pt-3">
                  <%= link_to new_user_session_path, class: "btn btn-outline-secondary" do %>
                    <i class="fas fa-sign-in-alt"></i>ログイン
                  <% end %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </header>

    <main>
      <!--フラッシュメッセージ-->
      <% flash.each do |key, value| %>
        <p class="alert alert-<%= key %> mt-3">
          <%= value %>
        </p>
      <% end %>

      <!--10秒かけてアラートを消す＋背景画像の高さ調整-->
      <script>
        $(function(){
          $(".alert").fadeOut(10000, hideYohaku);
          function hideYohaku(){
            $(".bg-slider").prev().offset({ top: 108 });
          }
        });
  　   </script>
      <%= yield %>
    </main>

    <footer class="shadow-sm">
      <div class="container">
        <p class="text-muted text-center">
          © All rights reserved by Otaka.
        </p>
      </div>
    </footer>
  </body>
</html>